
template32DoubleBracket = {
  'upper': [
    {
      'id': 1,
      'name': 'UB 1.1',
      'nextMatchId': 17,
      'nextLooserMatchId': 33,
      'participants': [],
    },
    {
      'id': 2,
      'name': 'UB 1.2',
      'nextMatchId': 17,
      'nextLooserMatchId': 33,
      'participants': [],
    },
    {
      'id': 3,
      'name': 'UB 1.3',
      'nextMatchId': 18,
      'nextLooserMatchId': 34,
      'participants': [],
    },
    {
      'id': 4,
      'name': 'UB 1.4',
      'nextMatchId': 18,
      'nextLooserMatchId': 34,
      'participants': [],
    },
    {
      'id': 5,
      'name': 'UB 1.5',
      'nextMatchId': 19,
      'nextLooserMatchId': 35,
      'participants': [],
    },
    {
      'id': 6,
      'name': 'UB 1.6',
      'nextMatchId': 19,
      'nextLooserMatchId': 35,
      'participants': [],
    },
    {
      'id': 7,
      'name': 'UB 1.7',
      'nextMatchId': 20,
      'nextLooserMatchId': 36,
      'participants': [],
    },
    {
      'id': 8,
      'name': 'UB 1.8',
      'nextMatchId': 20,
      'nextLooserMatchId': 36,
      'participants': [],
    },
    {
      'id': 9,
      'name': 'UB 1.9',
      'nextMatchId': 21,
      'nextLooserMatchId': 37,
      'participants': [],
    },
    {
      'id': 10,
      'name': 'UB 1.10',
      'nextMatchId': 21,
      'nextLooserMatchId': 37,
      'participants': [],
    },
    {
      'id': 11,
      'name': 'UB 1.11',
      'nextMatchId': 22,
      'nextLooserMatchId': 38,
      'participants': [],
    },
    {
      'id': 12,
      'name': 'UB 1.12',
      'nextMatchId': 22,
      'nextLooserMatchId': 38,
      'participants': [],
    },
    {
      'id': 13,
      'name': 'UB 1.13',
      'nextMatchId': 23,
      'nextLooserMatchId': 39,
      'participants': [],
    },
    {
      'id': 14,
      'name': 'UB 1.14',
      'nextMatchId': 23,
      'nextLooserMatchId': 39,
      'participants': [],
    },
    {
      'id': 15,
      'name': 'UB 1.15',
      'nextMatchId': 24,
      'nextLooserMatchId': 40,
      'participants': [],
    },
    {
      'id': 16,
      'name': 'UB 1.16',
      'nextMatchId': 24,
      'nextLooserMatchId': 40,
      'participants': [],
    },
    {
      'id': 17,
      'name': 'UB 2.1',
      'nextMatchId': 25,
      'nextLooserMatchId': 48,
      'participants': [],
    },
    {
      'id': 18,
      'name': 'UB 2.2',
      'nextMatchId': 25,
      'nextLooserMatchId': 47,
      'participants': [],
    },
    {
      'id': 19,
      'name': 'UB 2.3',
      'nextMatchId': 26,
      'nextLooserMatchId': 46,
      'participants': [],
    },
    {
      'id': 20,
      'name': 'UB 2.4',
      'nextMatchId': 26,
      'nextLooserMatchId': 45,
      'participants': [],
    },
    {
      'id': 21,
      'name': 'UB 2.5',
      'nextMatchId': 27,
      'nextLooserMatchId': 44,
      'participants': [],
    },
    {
      'id': 22,
      'name': 'UB 2.6',
      'nextMatchId': 27,
      'nextLooserMatchId': 43,
      'participants': [],
    },
    {
      'id': 23,
      'name': 'UB 2.7',
      'nextMatchId': 28,
      'nextLooserMatchId': 42,
      'participants': [],
    },
    {
      'id': 24,
      'name': 'UB 2.8',
      'nextMatchId': 28,
      'nextLooserMatchId': 41,
      'participants': [],
    },
    {
      'id': 25,
      'name': 'UB 3.1',
      'nextMatchId': 29,
      'nextLooserMatchId': 56,
      'participants': [],
    },
    {
      'id': 26,
      'name': 'UB 3.2',
      'nextMatchId': 29,
      'nextLooserMatchId': 55,
      'participants': [],
    },
    {
      'id': 27,
      'name': 'UB 3.3',
      'nextMatchId': 30,
      'nextLooserMatchId': 54,
      'participants': [],
    },
    {
      'id': 28,
      'name': 'UB 3.4',
      'nextMatchId': 30,
      'nextLooserMatchId': 53,
      'participants': [],
    },
    {
      'id': 29,
      'name': 'UB 4.1',
      'nextMatchId': 31,
      'nextLooserMatchId': 60,
      'participants': [],
    },
    {
      'id': 30,
      'name': 'UB 4.2',
      'nextMatchId': 31,
      'nextLooserMatchId': 59,
      'participants': [],
    },
    {
      'id': 31,
      'name': 'UB Semi Final',
      'nextMatchId': 32,
      'nextLooserMatchId': 62,
      'participants': [],
    },
    {
      'id': 32,
      'name': 'Final',
      'participants': [],
    },
  ],
  'lower': [
    {
      'id': 33,
      'name': 'LB 1.1',
      'nextMatchId': 41,
      'participants': [],
    },
    {
      'id': 34,
      'name': 'LB 1.2',
      'nextMatchId': 42,
      'participants': [],
    },
    {
      'id': 35,
      'name': 'LB 1.3',
      'nextMatchId': 43,
      'participants': [],
    },
    {
      'id': 36,
      'name': 'LB 1.4',
      'nextMatchId': 44,
      'participants': [],
    },
    {
      'id': 37,
      'name': 'LB 1.5',
      'nextMatchId': 45,
      'participants': [],
    },
    {
      'id': 38,
      'name': 'LB 1.6',
      'nextMatchId': 46,
      'participants': [],
    },
    {
      'id': 39,
      'name': 'LB 1.7',
      'nextMatchId': 47,
      'participants': [],
    },
    {
      'id': 40,
      'name': 'LB 1.8',
      'nextMatchId': 48,
      'participants': [],
    },
    {
      'id': 41,
      'name': 'LB 2.1',
      'nextMatchId': 49,
      'participants': [],
    },
    {
      'id': 42,
      'name': 'LB 2.2',
      'nextMatchId': 50,
      'participants': [],
    },
    {
      'id': 43,
      'name': 'LB 2.3',
      'nextMatchId': 51,
      'participants': [],
    },
    {
      'id': 44,
      'name': 'LB 2.4',
      'nextMatchId': 52,
      'participants': [],
    },
    {
      'id': 45,
      'name': 'LB 2.5',
      'nextMatchId': 53,
      'participants': [],
    },
    {
      'id': 46,
      'name': 'LB 2.6',
      'nextMatchId': 54,
      'participants': [],
    },
    {
      'id': 47,
      'name': 'LB 2.7',
      'nextMatchId': 55,
      'participants': [],
    },
    {
      'id': 48,
      'name': 'LB 2.8',
      'nextMatchId': 56,
      'participants': [],
    },
    {
      'id': 49,
      'name': 'LB 3.1',
      'nextMatchId': 53,
      'participants': [],
    },
    {
      'id': 50,
      'name': 'LB 3.2',
      'nextMatchId': 54,
      'participants': [],
    },
    {
      'id': 51,
      'name': 'LB 3.3',
      'nextMatchId': 55,
      'participants': [],
    },
    {
      'id': 52,
      'name': 'LB 3.4',
      'nextMatchId': 56,
      'participants': [],
    },
    {
      'id': 53,
      'name': 'LB 4.1',
      'nextMatchId': 57,
      'participants': [],
    },
    {
      'id': 54,
      'name': 'LB 4.2',
      'nextMatchId': 57,
      'participants': [],
    },
    {
      'id': 55,
      'name': 'LB 4.3',
      'nextMatchId': 58,
      'participants': [],
    },
    {
      'id': 56,
      'name': 'LB 4.4',
      'nextMatchId': 58,
      'participants': [],
    },
    {
      'id': 57,
      'name': 'LB 5.1',
      'nextMatchId': 59,
      'participants': [],
    },
    {
      'id': 58,
      'name': 'LB 5.2',
      'nextMatchId': 60,
      'participants': [],
    },
    {
      'id': 59,
      'name': 'LB 6.1',
      'nextMatchId': 61,
      'participants': [],
    },
    {
      'id': 60,
      'name': 'LB 6.2',
      'nextMatchId': 61,
      'participants': [],
    },
    {
      'id': 61,
      'name': 'LB 7.1',
      'nextMatchId': 62,
      'participants': [],
    },
    {
      'id': 62,
      'name': 'LB Semi Final',
      'nextMatchId': 32,
      'participants': [],
    },
  ],
}