
template16DoubleBracket = {
  'upper': [
    {
      'id': 30,
      'name': 'UB 1.1',
      'nextMatchId': 18,
      'nextLooserMatchId': 17,
      'participants': [],
    },
    {
      'id': 29,
      'name': 'UB 1.2',
      'nextMatchId': 18,
      'nextLooserMatchId': 17,
      'participants': [],
    },
    {
      'id': 28,
      'name': 'UB 1.3',
      'nextMatchId': 17,
      'nextLooserMatchId': 22,
      'participants': [],
    },
    {
      'id': 27,
      'name': 'UB 1.4',
      'nextMatchId': 17,
      'nextLooserMatchId': 22,
      'participants': [],
    },
    {
      'id': 26,
      'name': 'UB 1.5',
      'nextMatchId': 16,
      'nextLooserMatchId': 20,
      'participants': [],
    },
    {
      'id': 25,
      'name': 'UB 1.6',
      'nextMatchId': 16,
      'nextLooserMatchId': 20,
      'participants': [],
    },
    {
      'id': 24,
      'name': 'UB 1.7',
      'nextMatchId': 15,
      'nextLooserMatchId': 19,
      'participants': [],
    },
    {
      'id': 23,
      'name': 'UB 1.8',
      'nextMatchId': 15,
      'nextLooserMatchId': 19,
      'participants': [],
    },
    {
      'id': 18,
      'name': 'UB 2.1',
      'nextMatchId': 6,
      'nextLooserMatchId': 15,
      'participants': [],
    },
    {
      'id': 17,
      'name': 'UB 2.2',
      'nextMatchId': 6,
      'nextLooserMatchId': 16,
      'participants': [],
    },
    {
      'id': 16,
      'name': 'UB 2.3',
      'nextMatchId': 5,
      'nextLooserMatchId': 17,
      'participants': [],
    },
    {
      'id': 15,
      'name': 'UB 2.4',
      'nextMatchId': 5,
      'nextLooserMatchId': 18,
      'participants': [],
    },
    {
      'id': 6,
      'name': 'UB 3.1',
      'nextMatchId': 2,
      'nextLooserMatchId': 7,
      'participants': [],
    },
    {
      'id': 5,
      'name': 'UB 3.2',
      'nextMatchId': 2,
      'nextLooserMatchId': 8,
      'participants': [],
    },
    {
      'id': 2,
      'name': 'UB Semi Final',
      'nextMatchId': 1,
      'nextLooserMatchId': 3,
      'participants': [],
    },
    {
      'id': 1,
      'name': 'Final',
      'participants': [],
    },
  ],
  'lower': [
    {
      'id': 22,
      'name': 'LB 1.1',
      'nextMatchId': 18,
      'participants': [],
    },
    {
      'id': 21,
      'name': 'LB 1.2',
      'nextMatchId': 17,
      'participants': [],
    },
    {
      'id': 20,
      'name': 'LB 1.3',
      'nextMatchId': 16,
      'participants': [],
    },
    {
      'id': 19,
      'name': 'LB 1.4',
      'nextMatchId': 15,
      'participants': [],
    },
    {
      'id': 18,
      'name': 'LB 2.1',
      'nextMatchId': 10,
      'participants': [],
    },
    {
      'id': 17,
      'name': 'LB 2.2',
      'nextMatchId': 10,
      'participants': [],
    },
    {
      'id': 16,
      'name': 'LB 2.3',
      'nextMatchId': 9,
      'participants': [],
    },
    {
      'id': 15,
      'name': 'LB 2.4',
      'nextMatchId': 9,
      'participants': [],
    },
    {
      'id': 10,
      'name': 'LB 3.1',
      'nextMatchId': 8,
      'participants': [],
    },
    {
      'id': 9,
      'name': 'LB 3.2',
      'nextMatchId': 7,
      'participants': [],
    },
    {
      'id': 8,
      'name': 'LB 4.1',
      'nextMatchId': 4,
      'participants': [],
    },
    {
      'id': 7,
      'name': 'LB 4.2',
      'nextMatchId': 4,
      'participants': [],
    },
    {
      'id': 4,
      'name': 'LB 5.1',
      'nextMatchId': 3,
      'participants': [],
    },
    {
      'id': 3,
      'name': 'LB Semi Final',
      'nextMatchId': 1,
      'participants': [],
    },
  ],
}